# platform list
platforms:
- itg
- prp
- prod
# default platform
default-platform: itg
# platform where init is forbidden
critical-platforms:
- prod
# directory for SQL scripts (relative to this file)
sql-dir: sql
# charset of the database
database-charset: utf8
# Database configuration for environments
database:
  itg:
    hostname: localhost
    database: test
    password: test
    username: test
  prp:
    hostname: localhost
    database: test
    password: test
    username: test
  prod:
    hostname: localhost
    database: test
    password: test
    username: test
